version: "3"
services:
  python:
    container_name: pythonimg
    build: .
    restart: always
    ports:
      - 5001:5001
    networks:
      - test_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - test_network
    volumes:
      - db-data:/data/db

  nginx:
    image: nginx:latest
    container_name: web
    restart: always
    ports:
      - 80:80
    networks:
      - test_network
    depends_on:
      - python
    volumes:
      - nginxconf:/var/lib/nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  db-data:
   external: true
  nginxconf:
   external: true
networks:
  test_network:
    external: true